[2025-02-27 19:53:13,232 log_parser.py:59 INFO] Sucessfully loaded MLPerf log from closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b/Offline/accuracy/mlperf_log_detail.txt.
[2025-02-27 19:53:13,233 log_parser.py:59 INFO] Sucessfully loaded MLPerf log from closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b/Offline/performance/run_1/mlperf_log_detail.txt.
[2025-02-27 19:53:13,234 log_parser.py:59 INFO] Sucessfully loaded MLPerf log from closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b/Offline/performance/run_1/mlperf_log_detail.txt.
[2025-02-27 19:53:13,234 submission_checker.py:1516 INFO] Target latency: None, Latency: 12499463290639, Scenario: Offline
[2025-02-27 19:53:13,234 submission_checker.py:2629 ERROR] closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b does not have all required scenarios, missing {'Server'}
[2025-02-27 19:53:13,235 submission_checker.py:3167 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3171 INFO] Results closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b/Offline 428.895
[2025-02-27 19:53:13,235 submission_checker.py:3173 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3176 ERROR] NoResults closed/HPE/results/HPE_PROLIANT_DL380A_H200_NVL_141GBX8_TRT/llama3_1-405b
[2025-02-27 19:53:13,235 submission_checker.py:3262 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3263 INFO] Results=1, NoResults=1, Power Results=0
[2025-02-27 19:53:13,235 submission_checker.py:3270 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3271 INFO] Closed Results=1, Closed Power Results=0

[2025-02-27 19:53:13,235 submission_checker.py:3276 INFO] Open Results=0, Open Power Results=0

[2025-02-27 19:53:13,235 submission_checker.py:3281 INFO] Network Results=0, Network Power Results=0

[2025-02-27 19:53:13,235 submission_checker.py:3286 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3288 INFO] Systems=1, Power Systems=0
[2025-02-27 19:53:13,235 submission_checker.py:3292 INFO] Closed Systems=1, Closed Power Systems=0
[2025-02-27 19:53:13,235 submission_checker.py:3297 INFO] Open Systems=0, Open Power Systems=0
[2025-02-27 19:53:13,235 submission_checker.py:3302 INFO] Network Systems=0, Network Power Systems=0
[2025-02-27 19:53:13,235 submission_checker.py:3307 INFO] ---
[2025-02-27 19:53:13,235 submission_checker.py:3309 ERROR] SUMMARY: submission has errors
